openapi: 3.0.0
info:
  version: '1.0.0'
  title: Watcher security-critical API
  description: >
    API specification of the Watcher's security-critical Service
    
    Error codes are available in **FIXME** [html](./errors), [json](./errors.json)
    and [yaml](./errors.yaml) formats.
  contact:
    name: OmiseGO
    email: omisego@omisego.co
  license:
    name: 'Apache 2.0: https://www.apache.org/licenses/LICENSE-2.0'
    url: 'https://omisego.network/'

tags:
  - name: Security
    description: Security related API.
  - name: UTXO
    description: UTXO related API.
  - name: InflightExit
    description: InflightExit related API.    

paths:
  /account.get_utxos:
    post:
      tags:
        - UTXO
      summary: Gets all utxos belonging to the given address.
      description: >
        Note that this is a performance intensive call and should only be used if the chain is byzantine and the user needs to retrieve utxo information to be able to exit.
        Normally an application should use the Informational API's [Account - Get Utxos](http://TODO) instead.
        This version is provided in case the Informational API is not available.
      operationId: getUtxos
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/requests/GetUtxosOpId'
      responses:
        200:
          $ref: '#/responses/GetUtxosOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /utxo.get_challenge_data:
    post:
      tags:
        - UTXO
      summary: Gets challenge data for a given utxo exit.
      description:
      operationId: getUtxoChallenge
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/definitions/UtxoPosBodySchema'
      responses:
        200:
          $ref: '#/responses/GetUtxoChallengeOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /utxo.get_exit_data:
    post:
      tags:
        - UTXO
      summary: Gets exit data for a given utxo.
      description:
      operationId: getUtxoExit
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/definitions/UtxoPosBodySchema'
      responses:
        200:
          $ref: '#/responses/GetUtxoExitOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /transaction.submit:
    post:
      tags:
        - Security
      summary: Sends transaction to Child chain.
      description: Watcher passes signed transaction to the child chain only if it's secure (better explaination needed)
      operationId: submit
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/definitions/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/SubmitOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /status:
    post:
      tags:
        - Security
      summary: Returns information about the current state of the child chain and the watcher.
      description: >
        The most critical function of the Watcher is to monitor the ChildChain and report dishonest activity.
        The user must call the `/status` endpoint periodically to check. Any situation that requires the user 
        to either exit or challenge an invalid exit will be included in the `byzantine_events` field.
      operationId: status
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          $ref: '#/responses/StatusOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /inflight_exit.get_data:
    post:
      tags:
        - InflightExit
      summary: Gets exit data for an in-flight exit. 
      description: Exit data are arguments to `startInFlightExit` root chain contract function.
      operationId: getInFlightExit
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/definitions/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/GetInFlightExitOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'          
  /inflight_exit.get_competitor:
    post:
      tags:
        - InflightExit
      summary: Returns a competitor to an in-flight exit.
      description: Note that if the competing transaction has not been put into a block `competing_txid` and `competing_proof` will not be returned.
      operationId: getCompetitor
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/definitions/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/GetCompetitorOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /inflight_exit.prove_canonical:
    post:
      tags:
        - InflightExit
      summary: Proves transaction is canonical. 
      description: To respond to a challenge to an in-flight exit, this proves that the transaction has been put into a block (and therefore is canonical).
      operationId: proveCanonical
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/definitions/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/ProveCanonicalOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'

requests:
  GetUtxosOpId:
    description: HEX-encoded address of the account
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            address:
              type: string
              format: binary
            required:
              - address
          example:
            address: '0xb3256026863eb6ae5b06fa396ab09069784ea8ea'

responses:
  GetUtxosOpId: 
    description: Account utxos succcessful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: array
                items:
                - $ref: '#/definitions/UtxoSchema'
            example:
              data:
              - 
                blknum: 123000
                txindex: 111
                oindex: 0
                utxo_pos: 10000000010000000
                owner: '0xb3256026863eb6ae5b06fa396ab09069784ea8ea'
                currency: '0x0000000000000000000000000000000000000000'
                amount: 10
  GetUtxoChallengeOpId:
    description: Utxo challenge successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  input_index:
                    type: integer
                    format: int8
                  output_id:
                    type: integer
                    format: int256                
                  sig:
                    type: string
                    format: binary
                  txbytes:
                    type: string
                    format: binary
            example:
              data:
                input_index: 0
                output_id: 3000000000000
                sig: '0x6bfb9b2dbe32...'
                txbytes: '0x3eb6ae5b06f3...'
  GetUtxoExitOpId:
    description: Utxo challenge successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  utxo_pos:
                    type: integer
                    format: int256                
                  txbytes:
                    type: string
                    format: binary
                  proof:
                    type: string
                    format: binary     
            example:
              data:
                utxo_pos: 10000000010000000
                txbytes: '0x3eb6ae5b06f3'
                proof: '0xcedb8b31d1e4'
  SubmitOpId:
    description: Transaction submission successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  blknum:
                    type: integer
                    format: int64
                  txindex:
                    type: integer
                    format: int16
                  txhash:
                    type: string
                    format: binary
            example:
              data:
                blknum: 123000
                txindex: 111
                txhash: '0xbdf562c24ace032176e27621073df58ce1c6f65de3b5932343b70ba03c72132d'
  StatusOpId:
    description: Status successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  last_validated_child_block_number:
                    type: integer
                    format: int64                  
                  last_mined_child_block_timestamp:
                    type: integer
                    format: int64                  
                  last_mined_child_block_number:
                    type: integer
                    format: int64                  
                  eth_syncing:
                    type: boolean
                  byzantine_events:
                    type: array                  
                  inflight_txs:
                    type: array                  
                  inflight_exits:
                    type: array                  
            example:
              data:
                last_validated_child_block_number: 10000
                last_mined_child_block_timestamp: 1535031020
                last_mined_child_block_number: 11000
                eth_syncing: true
                byzantine_events:
                -
                  event: invalid_exit
                  details:
                    eth_height: 615440
                    utxo_pos: 10000000010000000
                    owner: '0xb3256026863eb6ae5b06fa396ab09069784ea8ea'
                    currency: '0x0000000000000000000000000000000000000000'
                    amount: 100
                inflight_txs:
                -
                  txhash: '0xbdf562c24ace032176e27621073df58ce1c6f65de3b5932343b70ba03c72132d'
                  txbytes: '0x3eb6ae5b06f3...'
                  input_addresses:
                  - '0x1234...'
                  ouput_addresses:
                  - '0x1234...'
                  - '0x7890...'
                inflight_exits:
                -
                  txhash: '0x5df13a6bf96dbcf6e66d8babd6b55bd40d64d4320c3b115364c6588fc18c2a21'
                  txbytes: '0xf3170101c094...'
                  eth_height: 615441
                  piggybacked_inputs: 
                  - 1
                  piggybacked_outputs:
                  - 0
                  - 1
  GetInFlightExitOpId:
    description: Get in-flight exit successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  in_flight_tx:
                    type: string
                    format: binary
                  input_txs:
                    type: string
                    format: binary
                  input_txs_inclusion_proofs:
                    type: string
                    format: binary
                  in_flight_tx_sigs:
                    type: string
                    format: binary
            example:
              data:
                in_flight_tx: '0xf3170101c0940000...'
                input_txs: '0xa3470101c0940000...'
                input_txs_inclusion_proofs : '0xcedb8b31d1e4...'
                in_flight_tx_sigs : '0x6bfb9b2dbe32...'
  GetCompetitorOpId:
    description: Get competitor successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  inflight_txbytes:
                    type: string
                    format: binary
                  inflight_input_index:
                    type: integer
                    format: int8
                  competing_txbytes:
                    type: string
                    format: binary
                  competing_input_index:
                    type: integer
                    format: int8
                  competing_sig:
                    type: string
                    format: binary
                  competing_txid:
                    type: integer
                    format: int256
                  competing_proof:
                    type: string
                    format: binary
            example:
              data:
                inflight_txbytes: '0xf3170101c0940000...'
                inflight_input_index: 1
                competing_txbytes: '0x5df13a6bee20000...'
                competing_input_index: 1
                competing_sig: '0xa3470101c0940000...'
                competing_txid: 2600003920012
                competing_proof: '0xcedb8b31d1e4...'
  ProveCanonicalOpId:
    description: Prove canonical successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  inflight_txbytes:
                    type: string
                    format: binary
                  inflight_txid:
                    type: integer
                    format: int256
                  inflight_proof:
                    type: string
                    format: binary
            example:
              data:
                inflight_txbytes: '0xf3170101c0940000...'
                inflight_txid: 2600003920012
                inflight_proof: '0xcedb8b31d1e4...'

definitions:
  UtxoSchema:
    schema:
      type: object
      properties:
        blknum:
          type: integer
          format: int64
        txindex:
          type: integer
          format: int16
        oindex:
          type: integer
          format: int8
        utxo_pos:
          type: integer
          format: int256
        owner:
          type: string
          format: binary
        currency:
          type: string
          format: binary                
        amount:
          type: integer
          format: int256
  
  UtxoPosBodySchema:
    description: Utxo position (encoded as single integer, the way contract represents them)
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            utxo_pos:
              type: integer
              format: int256
          example:
            utxo_pos: 10000000010000000
  
  TransactionBodySchema:
    description: Signed transaction RLP-encoded to bytes and HEX-encoded to string
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            transaction:
              type: string
              format: binary  
          example:
            transaction: '0xf8d083015ba98080808080940000...'       
